# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='task',
            new_name='tasks',
        ),
    ]
