# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task',
            field=models.ManyToManyField(blank=True, to='todo.Task'),
        ),
    ]
