# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20170710_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='percentage_complete',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
