# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_task_percentage_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Employee'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
