# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20170717_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='milestones', to='todo.Milestone'),
        ),
    ]
