# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20170717_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
