# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
